### ISSUE TITLE
Re-enable CheckConfig / DiffConfig

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#244]
There was an error in pulumi-aws where the assumeRole config was being created as the following raw schema:

```
Config: {
               "skip_metadata_api_check": bool(false),
               "assume_role":             []interface {}{
                   "{\"roleArn\":\"arn:aws:iam::894850187425:role/stack72-assume-role\",\"sessionName\":\"gh-bug\"}",
               },
               "secret_key":                  "",
               "insecure":                    bool(false),
               "access_key":                  "",
               "skip_requesting_account_id":  bool(false),
               "token":                       "",
               "max_retries":                 int(25),
               "s3_force_path_style":         bool(false),
               "skip_get_ec2_platforms":      bool(false),
               "skip_region_validation":      bool(false),
               "profile":                     "",
               "region":                      "us-west-2",
               "skip_credentials_validation": bool(false),
               "shared_credentials_file":     "",
           },
```

Notice the `roleArn` and `sessionName`  inside the `assume_role` block - this is the problem - it seems like nested properties of the Config are not being named correctly

**Comment by EvanBoyle** [comment]
This can lead to some pretty gnarly errors:

```ts
const providerName = "name1";
const awsProvider = new aws.Provider(providerName, {
    region: "us-east-1",
});

const queue = new aws.sqs.Queue("queue", {}, { provider: awsProvider})
const bucket = new aws.s3.Bucket("my-bucket", {}, { provider: awsProvider });
```

Doing an update, then changing the region, then doing another update, followed finally by a destroy results in the following:

```
    error: deleting urn:pulumi:test::providerAlias::aws:s3/bucket:Bucket::my-bucket: 1 error occurred:
    	* error deleting S3 Bucket (my-bucket-b3ca77d): BucketRegionError: incorrect region, the bucket is not in 'us-west-1' region at endpoint ''
    	status code: 301, request id: , host id:
 
  pulumi:pulumi:Stack (providerAlias-test):
    error: update failed
 
  aws:sqs:Queue (queue):
    error: deleting urn:pulumi:test::providerAlias::aws:sqs/queue:Queue::queue: 1 error occurred:
    	* AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
    	status code: 400, request id: 7ef3b7ce-88b3-5539-9990-eea853424fa0
```

To fix the stack, you have to change the provider region back, do another update, and then finally the destroy will complete successfully.

**Comment by t0yv0** [comment]
Possibly related https://github.com/pulumi/pulumi-terraform-bridge/issues/651

**Comment by t0yv0** [comment]
We've re-enabled CheckConfig in https://github.com/pulumi/pulumi-terraform-bridge/pull/991 

To close this out we still need to re-enable DiffConfig. Related scenario for testing out DiffConfig re-enablement:
https://github.com/pulumi/pulumi/issues/1391

**Comment by t0yv0** [comment]
Chatting with @kpitzen here (CC @AaronFriel) - the remaining work is implementing DiffConfig and rolling it out. We briefly discussed rollout concerns from the provider team - it should be sufficient to flag DiffConfig by-default-off and add tests so that the provider team is in control off the rollout timing per-provider. More advanced strategies like shadow mode + warnings are not perceived necessary.

**Comment by t0yv0** [comment]
Looking at this today with @VenelinMartinov , there's a suspicion that the motivating bucket issue is already fixed (but we'll double check). Seems good to do this still from completeness POV.

**Comment by VenelinMartinov** [comment]
I was wrong about the bucket issue no longer being relevant - just tested this and the problem still reproduces.

I was under the impression that because we don't have DiffConfig we'd always replace the provider when there is a change but that is NOT the case - changing the region produces an update instead of a replace currently.

**Comment by VenelinMartinov** [comment]
@iwahbe - I believe we recently discussed this behaviour around property changes replacing the provider - you might find this interesting. I believe it is just the name of the provider which causes replacements.

**Comment by iwahbe** [comment]
> @iwahbe - I believe we recently discussed this behaviour around property changes replacing the provider - you might find this interesting. I believe it is just the name of the provider which causes replacements.

@VenelinMartinov Thanks for tagging me. It's definitely interesting. Do you know if `DiffConfig` would allow us to override the changing behavior? If not, then I think that https://github.com/pulumi/pulumi-terraform-bridge/issues/1631 is an engine bug.

**Comment by iwahbe** [comment]
I have confirmed that implementing `DiffConfig` resolves the problem. #1631 is not an engine bug.

**Comment by iwahbe** [comment]
@t0yv0 Why are we re-opening this issue? https://github.com/pulumi/pulumi-aws/issues/3826 looks like a bug (or at least an issue) in the bridge, but we did enable CheckConfig/DiffConfig. Can we open a new issue instead?
